### ISSUE TITLE
Annotations in COCO format

### ISSUE THREAD

**Issue by rusvagzur** [bupt-ai-cz/LLVIP#10]
Hi,

Do you have these annotations in COCO format? Or a script to convert them? 

Thanks

**Comment by SantJay** [comment]
Sorry, there are no related scripts yet:). We will consider updating our toolbox if necessary, you can keep following our Github.

**Comment by SantJay** [comment]
Now we provide a script for the conversion. See https://github.com/bupt-ai-cz/LLVIP/blob/main/toolbox/toolbox_readme.md.
