### ISSUE TITLE
。

### ISSUE THREAD

**Issue by Hiram1026** [bupt-ai-cz/LLVIP#11]

**Comment by Hiram1026** [comment]
好的 https://github.com/DocF/multispectral-object-detection
顺便请问一下你们CVF openaccess的文章能提供一下吗？

**Comment by SantJay** [comment]
您提供的这篇文章确实用了[CVF openaccess版本LLVIP](https://openaccess.thecvf.com/content/ICCV2021W/RLQ/papers/Jia_LLVIP_A_Visible-Infrared_Paired_Dataset_for_Low-Light_Vision_ICCVW_2021_paper.pdf)上的旧数据。其实应该以我们GitHub上的新数据为准，新数据也同步在了[Arxiv版本LLVIP](https://arxiv.org/pdf/2108.10831.pdf)上。

**Comment by Hiram1026** [comment]
目前从你们homepage取得的应该是最新的吧，顺便请问一下新老数据有没有明显的区分方式

**Comment by SantJay** [comment]
我们从未发布过旧数据集，从[homepage](https://bupt-ai-cz.github.io/LLVIP/)上获取的就是最新的:)。

**Comment by Hiram1026** [comment]
请问下你们训练时的配置，什么显卡，最后是用的best.pt吗？

我在yolo上跑，自己用的rtx3090  imgz=1280 batchsize=8,我跑出了下面的结果，这个结果较高，我有点怀疑我的实验结果
![image](https://user-images.githubusercontent.com/86820620/166876396-92f2262b-e130-4072-84a3-1295c8346c42.png)
我是用的best.pt基本上在50个epoch内就能取到了。

![image](https://user-images.githubusercontent.com/86820620/166876640-69339245-8f7f-4764-b58c-8fcf965b0696.png)

**Comment by SantJay** [comment]
我们使用的显卡是Tesla T4，测试模型使用的last.pt，imgz=1280，batchsize = 8

**Comment by XueZ-phd** [comment]
> 请问下你们训练时的配置，什么显卡，最后是用的best.pt吗？
> 
> 我在yolo上跑，自己用的rtx3090 imgz=1280 batchsize=8,我跑出了下面的结果，这个结果较高，我有点怀疑我的实验结果 ![image](https://user-images.githubusercontent.com/86820620/166876396-92f2262b-e130-4072-84a3-1295c8346c42.png) 我是用的best.pt基本上在50个epoch内就能取到了。
> 
> ![image](https://user-images.githubusercontent.com/86820620/166876640-69339245-8f7f-4764-b58c-8fcf965b0696.png)



> 我们使用的显卡是Tesla T4，测试模型使用的last.pt，imgz=1280，batchsize = 8，模型结构yolov5l。

我也有同样的问题。我想知道作者在[arxiv v3](https://arxiv.org/abs/2108.10831)版本中使用的yolov5l是什么版本的？正如 @Hiram1026 所言，不同版本的yolov5l获得的结果是不同的，规律基本上是越新的版本结果越好。
我将作者3个版本中的结果汇总如下，按照作者发表的时间，我猜测使用的是YOLOv5L 5.0 version。为了能够与作者的结果进行公平对比，我想知道作者的YOLOv5L版本号是什么。
![image](https://user-images.githubusercontent.com/58646903/202065067-551cb454-52bc-4de9-8a5e-6dcd1bbbf98f.png)

**Comment by XueZ-phd** [comment]
> 我们Arxiv v3版本中使用的yolov5l版本为version5.0，各位可以参考一下。

感谢回复！

**Comment by heitorrapela** [comment]
I saw that here you have test other versions of yolo. I have these results with the yolov5l (version 7.0) (commit: [bfa1f23](https://github.com/ultralytics/yolov5/tree/bfa1f23045c7c4136a9b8ced9d6be8249ed72692))  on llvip infrared trained with the hparams from this repo.

infrared single modality
![image](https://user-images.githubusercontent.com/14017613/204105741-41141ccb-1f0d-4e80-a89f-890385fe560b.png)

rgb single modality
![image](https://user-images.githubusercontent.com/14017613/204105917-a3a687f8-233c-4548-9da5-d6568db52a04.png)
