### ISSUE TITLE
Whether the object detection task uses early stopping strategy or not?

### ISSUE THREAD

**Issue by challow0** [bupt-ai-cz/LLVIP#24]
Hello ~
Just like the title, I want to know if the task trained completely for 200 epochs or just stopped in the epochs without improvement?

**Comment by SantJay** [comment]
Yes, we used this strategy. Even though we set 200 epochs, the training stops when there is no improvement for a long time.

**Comment by challow0** [comment]
@SantJay  So the argument `--patience` setting is 100 right?

**Comment by challow0** [comment]
Okk， thanks for your help~
