### ISSUE TITLE
The yolov5 and yolov3 model weight format may not be matched

### ISSUE THREAD

**Issue by BubblyYi** [bupt-ai-cz/LLVIP#25]
Hi,

Thanks for your amazing work!

When I use the weight of the yolov5 model which was downloaded from https://drive.google.com/file/d/1SPbr0PDiItape602-g-bstkX0P7NZo0q/view, I find that the format you provide is 'yolov5_ trained_ model.rar', but the code only supports .pt, .onnx, .tflite, .pb formats.

Looking forward to your reply.

**Comment by SantJay** [comment]
You can load the model after unzipping the `.rar` file :).

**Comment by BubblyYi** [comment]
> You can load the model after unzipping the `.rar` file :).

Hi,
I have been found that problems, thank you very much.
