### ISSUE TITLE
Number of image pairs for CVC-14 dataset in paper

### ISSUE THREAD

**Issue by zzowenzz** [bupt-ai-cz/LLVIP#34]
Hi maintainer:

Thanks for providing this awesome dataset. It is amazing.
I try to summarise popular datasets in this domain, and I found that the number of image pairs in CVC-14 dataset should be 8490, instead of 849 in Table 1. 

I download the CVC-14 dataset from (http://adas.cvc.uab.es/elektra/enigma-portfolio/cvc-14-visible-fir-day-night-pedestrian-sequence-dataset/)

**Comment by bupt-ai-cz** [comment]
Thanks for pointing out this. We will update the arXiv version later.
